const cfg = window.NHRP_CONFIG || {};
const configured = !!(cfg.SUPABASE_URL && !cfg.SUPABASE_URL.includes('YOUR_PROJECT') && cfg.SUPABASE_ANON_KEY && !cfg.SUPABASE_ANON_KEY.includes('YOUR_SUPABASE'));
const sb = configured ? supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY) : null;

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const state = { user:null, profile:null, page:'dashboard', spawnCategory:'All', oneType:'All', f9Type:'All', f9Cost:'All', housingTier:'All', coinFilter:'outstanding' };
const SPAWN_CATEGORIES = ['Bike','Truck','LEO / EMS','Car / SUV','Items'];
const ONE_TYPES = ['Vehicles','Guns'];
const HOUSING_TIERS = ['Tier 1','Tier 2','Tier 3','MLO'];
const ROLE_LABELS = {owner:'Owner',executive:'Executive',director:'Director',admin:'Admin',business_manager:'Business Manager',developer:'Developer',viewer:'Viewer'};
const APP_TABLES = ['businesses','factions','bans','spawn_codes','t_codes','one_of_ones','f9_items','staff','staff_training','payments','housing','admin_todos','activity_check_history','app_categories','coin_collections'];
const SYSTEM_PAGES = new Set(['backup','users','audit','settings']);
const CATEGORY_DEFAULTS = {
  payment_category: [],
  business_type: [],
  one_type: ['Vehicles','Guns'],
  housing_tier: ['Tier 1','Tier 2','Tier 3','MLO'],
  faction_type: [],
  spawn_category: ['Bike','Truck','LEO / EMS','Car / SUV','Items'],
  f9_type: [],
  staff_rank: [],
  training_name: [],
  tcode_category: ['General']
};
const CATEGORY_TARGETS = {
  payment_category:{table:'payments',column:'category',label:'Payment Categories'},
  business_type:{table:'businesses',column:'type',label:'Business Types'},
  one_type:{table:'one_of_ones',column:'type',label:'1 of 1 Categories'},
  housing_tier:{table:'housing',column:'housing_tier',label:'Housing Categories'},
  faction_type:{table:'factions',column:'type',label:'Faction Categories'},
  spawn_category:{table:'spawn_codes',column:'category',label:'Spawn Code Categories'},
  f9_type:{table:'f9_items',column:'type',label:'F9 Categories'},
  staff_rank:{table:'staff',column:'rank',label:'Staff Rank Categories'},
  training_name:{table:'staff_training',column:'training_name',label:'Training Categories'},
  tcode_category:{table:'t_codes',column:'category',label:'T/Code Categories'}
};


function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600);}
function today(){return new Date().toISOString().slice(0,10);}
function normalizeDate(v,fallback=null){
  if(v===null||v===undefined)return fallback;
  const s=String(v).trim();
  if(!s||['—','-','n/a','na','none','null','undefined'].includes(s.toLowerCase()))return fallback;
  let m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);
  if(m){
    const y=Number(m[1]),mo=Number(m[2]),d=Number(m[3]);
    const test=new Date(Date.UTC(y,mo-1,d));
    if(test.getUTCFullYear()===y&&test.getUTCMonth()===mo-1&&test.getUTCDate()===d)return `${String(y).padStart(4,'0')}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
    return fallback;
  }
  m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2}|\d{4})$/);
  if(m){
    const mo=Number(m[1]),d=Number(m[2]);let y=Number(m[3]);if(y<100)y+=2000;
    const test=new Date(Date.UTC(y,mo-1,d));
    if(test.getUTCFullYear()===y&&test.getUTCMonth()===mo-1&&test.getUTCDate()===d)return `${String(y).padStart(4,'0')}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
    return fallback;
  }
  const parsed=new Date(s);
  if(Number.isNaN(parsed.getTime()))return fallback;
  return parsed.toISOString().slice(0,10);
}
function dateOnly(v){return normalizeDate(v,null)||'—';}
function datefmt(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString();}
function addDaysIso(v,days){const base=normalizeDate(v,today());const d=new Date(`${base}T12:00:00`);d.setDate(d.getDate()+Number(days||0));return d.toISOString().slice(0,10);}
function money(v){return Number(v||0).toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2});}
function role(){return state.profile?.role||'viewer';}
function roleLabel(v){return ROLE_LABELS[v]||v||'Viewer';}
function canWrite(){return ['owner','executive','director','admin','business_manager','developer'].includes(role());}
function canDelete(){return ['owner','executive'].includes(role());}
function ownerOnly(){return ['owner','executive'].includes(role());}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden');}
function closeModal(){$('#modal').classList.add('hidden');}
function setHead(title,sub){$('#pageTitle').textContent=title;$('#pageSubtitle').textContent=sub;}
function badge(t,cls=''){return `<span class="badge ${cls}">${esc(t||'—')}</span>`;}
function code(v){return `<span class="code">${esc(v||'—')}</span>`;}
function field(label,name,value='',required=false,type='text',step=''){return `<label>${esc(label)}<input name="${esc(name)}" type="${esc(type)}" value="${esc(value??'')}" ${required?'required':''} ${step?`step="${step}"`:''}></label>`;}
function area(label,name,value='',required=false){return `<label class="full">${esc(label)}<textarea name="${esc(name)}" ${required?'required':''}>${esc(value??'')}</textarea></label>`;}
function selectField(label,name,opts,value){return `<label>${esc(label)}<select name="${esc(name)}">${opts.map(o=>{const val=typeof o==='string'?o:o.value;const text=typeof o==='string'?o:o.label;return `<option value="${esc(val)}" ${String(val)===String(value??'')?'selected':''}>${esc(text)}</option>`;}).join('')}</select></label>`;}
function formObj(form){const fd=new FormData(form),o={};for(const [k,v] of fd.entries())o[k]=v===''?null:v;return o;}
function panel(title,kicker,body,buttons=''){return `<div class="panel"><div class="panel-head"><div><div class="panel-kicker">${esc(kicker||'NHRP')}</div><h2>${esc(title)}</h2></div><div class="toolbar">${buttons}</div></div>${body}</div>`;}
function cellText(v){const el=document.createElement('div');el.innerHTML=String(v??'');return (el.textContent||'').trim();}
function copyableCell(v){const text=cellText(v);if(!text||text==='—')return v??'—';return `<span class="copy-value">${v??'—'}<button type="button" class="copy-btn" data-copy="${esc(text)}" onclick="event.stopPropagation();copyText(this.dataset.copy)">Copy</button></span>`;}
function table(headers,rows){const copyCols=new Set(['Spawn Code','Discord ID','Code']);return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${headers.map((h,i)=>`<td>${copyCols.has(String(h).trim())?copyableCell(r[i]):(r[i]??'—')}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="empty">No records found.</td></tr>`}</tbody></table></div>`;}
function stat(icon,label,value,sub){return `<div class="stat-card"><div class="stat-icon">${icon}</div><div class="stat-value">${esc(value)}</div><div class="stat-label">${esc(label)}</div><div class="stat-sub">${esc(sub)}</div></div>`;}
function standardActions(tableName,id,editFn){const edit=canWrite()?`<button class="btn secondary small" onclick="${editFn}('${id}')">Edit</button>`:'';const del=canDelete()?`<button class="btn danger small" onclick="deleteRow('${tableName}','${id}')">Delete</button>`:'';return edit||del?`<div class="actions">${edit}${del}</div>`:'';}

const SCREENSHOT_BUCKET='nhrp-screenshots';
function screenshotLink(url,label='View'){return url?`<a class="clickable" href="${esc(url)}" target="_blank" rel="noopener">${esc(label)}</a>`:'—';}
function screenshotDropField(id,current=''){
  return `<label class="full">Screenshot<div id="${esc(id)}" class="screenshot-drop ${current?'has-image':''}" tabindex="0">
    <input class="screenshot-file" type="file" accept="image/*" hidden>
    <input class="screenshot-url" type="hidden" name="screenshot_url" value="${esc(current||'')}">
    <div class="screenshot-drop-copy"><b>Hover Here + Ctrl+V</b><span>No click needed • You can also drag/drop an image • PNG / JPG / WEBP</span></div>
    <div class="screenshot-preview">${current?`<img src="${esc(current)}" alt="Screenshot preview"><a href="${esc(current)}" target="_blank" rel="noopener">Open current screenshot</a>`:''}</div>
    <button type="button" class="btn danger small screenshot-remove ${current?'':'hidden'}">Remove Screenshot</button>
  </div></label>`;
}
async function uploadScreenshot(file,folder){
  if(!file||!file.type?.startsWith('image/'))throw new Error('Please choose an image file.');
  const safe=(file.name||'screenshot.png').replace(/[^a-zA-Z0-9._-]+/g,'_');
  const path=`${folder}/${state.user?.id||'user'}/${Date.now()}_${safe}`;
  const {error}=await sb.storage.from(SCREENSHOT_BUCKET).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});
  if(error)throw error;
  const {data}=sb.storage.from(SCREENSHOT_BUCKET).getPublicUrl(path);
  return data.publicUrl;
}
function initScreenshotDrop(id,folder){
  const box=document.getElementById(id); if(!box)return;
  const input=box.querySelector('.screenshot-file'), hidden=box.querySelector('.screenshot-url'), preview=box.querySelector('.screenshot-preview'), remove=box.querySelector('.screenshot-remove'), copy=box.querySelector('.screenshot-drop-copy');
  const idleCopy=()=>{copy.innerHTML='<b>Hover Here + Ctrl+V</b><span>No click needed • You can also drag/drop an image • PNG / JPG / WEBP</span>';};
  const setPreview=url=>{hidden.value=url||'';box.classList.toggle('has-image',!!url);remove.classList.toggle('hidden',!url);preview.innerHTML=url?`<img src="${esc(url)}" alt="Screenshot preview"><a href="${esc(url)}" target="_blank" rel="noopener">Open screenshot</a>`:'';};
  const handle=async file=>{if(!file)return;copy.innerHTML='<b>Uploading screenshot...</b><span>Please wait</span>';try{const url=await uploadScreenshot(file,folder);setPreview(url);toast('Screenshot uploaded');}catch(err){toast(err.message||'Screenshot upload failed');}finally{idleCopy();input.value='';}};
  const pastedImage=e=>{const items=[...(e.clipboardData?.items||[])];for(const item of items){if(item.kind==='file'&&item.type?.startsWith('image/'))return item.getAsFile();}return [...(e.clipboardData?.files||[])].find(f=>f.type?.startsWith('image/'))||null;};
  const pasteHandler=e=>{const file=pastedImage(e);if(file){e.preventDefault();e.stopPropagation();handle(file);}};
  box.addEventListener('mouseenter',()=>{document.querySelectorAll('.screenshot-drop.paste-ready').forEach(x=>x.classList.remove('paste-ready'));box.classList.add('paste-ready');window.__nhrpPasteTarget=box;});
  box.addEventListener('mouseleave',()=>{box.classList.remove('paste-ready');if(window.__nhrpPasteTarget===box)window.__nhrpPasteTarget=null;});
  ['dragenter','dragover'].forEach(ev=>box.addEventListener(ev,e=>{e.preventDefault();box.classList.add('dragging');}));
  ['dragleave','drop'].forEach(ev=>box.addEventListener(ev,e=>{e.preventDefault();box.classList.remove('dragging');}));
  box.addEventListener('drop',e=>handle(e.dataTransfer?.files?.[0]));
  box.addEventListener('paste',pasteHandler);
  const docPaste=e=>{if(window.__nhrpPasteTarget===box)pasteHandler(e);};
  document.addEventListener('paste',docPaste);
  const observer=new MutationObserver(()=>{if(!document.body.contains(box)){document.removeEventListener('paste',docPaste);observer.disconnect();}});
  observer.observe(document.body,{childList:true,subtree:true});
  remove.addEventListener('click',e=>{e.stopPropagation();setPreview('');});
}

async function getCategories(scope,current='',existing=[]){
  const target=CATEGORY_TARGETS[scope];if(!target)return [];
  const {data=[],error}=await sb.from('app_categories').select('name').eq('scope',scope).order('sort_order').order('name');
  let names=error?[]:data.map(x=>x.name).filter(Boolean);
  if(!names.length)names=[...(CATEGORY_DEFAULTS[scope]||[])];
  if(current&&!names.includes(current))names.push(current);
  for(const v of existing||[])if(v&&!names.includes(v))names.push(v);
  return [...new Set(names)].sort((a,b)=>String(a).localeCompare(String(b)));
}
function categoryButton(scope){const x=CATEGORY_TARGETS[scope];return canWrite()&&x?`<button class="btn secondary" onclick="categoryManager('${scope}')">Manage Categories</button>`:'';}
window.categoryManager=async scope=>{
  const target=CATEGORY_TARGETS[scope];if(!target)return toast('Unknown category group');
  const {data=[],error}=await sb.from('app_categories').select('*').eq('scope',scope).order('sort_order').order('name');if(error)return toast(error.message);
  openModal(`<h3>${esc(target.label)}</h3><p class="muted">Add or rename categories here. Changes appear in dropdowns without uploading new website code.</p><form id="categoryAddForm" class="category-add"><input name="name" placeholder="New category" required><button class="btn primary">+ Add Category</button></form><div class="category-list">${data.length?data.map(r=>`<div class="category-row"><strong>${esc(r.name)}</strong><div class="actions"><button class="btn secondary small" onclick="renameCategory('${scope}','${r.id}','${encodeURIComponent(r.name)}')">Rename</button>${canDelete()?`<button class="btn danger small" onclick="deleteCategory('${scope}','${r.id}')">Delete</button>`:''}</div></div>`).join(''):'<div class="empty">No saved categories yet. Add one above.</div>'}</div><p class="small-note">Deleting a category removes it from future choices. Existing records are not deleted.</p>`);
  $('#categoryAddForm').onsubmit=async e=>{e.preventDefault();const name=String(new FormData(e.target).get('name')||'').trim();if(!name)return;const {error}=await sb.from('app_categories').upsert({scope,name},{onConflict:'scope,name'});if(error)return toast(error.message);await audit('create','app_categories',null,{scope,name});toast('Category added');categoryManager(scope);};
};
window.renameCategory=async(scope,id,oldEncoded)=>{const target=CATEGORY_TARGETS[scope];if(!target)return;const oldName=decodeURIComponent(oldEncoded);const name=prompt('New category name:',oldName);if(!name||name.trim()===oldName)return;const next=name.trim();const patch={};patch[target.column]=next;const {error:ue}=await sb.from(target.table).update(patch).eq(target.column,oldName);if(ue)return toast(ue.message);const {error}=await sb.from('app_categories').update({name:next}).eq('id',id);if(error)return toast(error.message);await audit('update','app_categories',id,{scope,from:oldName,to:next});toast('Category renamed');categoryManager(scope);};
window.deleteCategory=async(scope,id)=>{if(!canDelete())return toast('Owner / Executive delete permission required');if(!confirm('Remove this category from future choices? Existing records will keep their current value.'))return;const {error}=await sb.from('app_categories').delete().eq('id',id);if(error)return toast(error.message);await audit('delete','app_categories',id,{scope});toast('Category removed');categoryManager(scope);};

async function audit(action,entityType,entityId,details={}){if(!sb||!state.user)return;await sb.from('audit_logs').insert({user_id:state.user.id,action,entity_type:entityType,entity_id:entityId||null,details});}
async function count(t,filter){let q=sb.from(t).select('*',{count:'exact',head:true});if(filter)q=filter(q);const {count}=await q;return count||0;}

async function boot(){
  if(!configured){$('#loginView').classList.remove('hidden');$('#loginError').innerHTML='Setup required: copy your working Supabase URL and Publishable Key into <b>config.js</b>.';return;}
  const {data:{session}}=await sb.auth.getSession();
  if(session)await setSession(session);else $('#loginView').classList.remove('hidden');
}
async function setSession(session){
  state.user=session.user;
  try{await sb.rpc('sync_discord_profile');}catch(_){ }
  const {data,error}=await sb.from('profiles').select('*').eq('id',session.user.id).single();
  if(error||!data){$('#loginView').classList.remove('hidden');$('#loginError').textContent='Could not load your Command Center profile.';return;}
  state.profile=data;$('#loginView').classList.add('hidden');
  if(!data.active){$('#pendingView').classList.remove('hidden');$('#appView').classList.add('hidden');$('#pendingDiscordId').textContent=data.discord_id||'Not available';return;}
  $('#pendingView').classList.add('hidden');$('#appView').classList.remove('hidden');
  $('#userName').textContent=data.display_name||'NHRP User';$('#userRole').textContent=roleLabel(data.role);$('#userDiscord').textContent=data.discord_name||data.discord_id||'';
  $$('.owner-only').forEach(x=>x.classList.toggle('hidden',!ownerOnly()));
  await render();
}

$('#discordLoginBtn').addEventListener('click',async()=>{if(!sb)return;$('#loginError').textContent='';const redirectTo=window.location.origin+window.location.pathname;const {error}=await sb.auth.signInWithOAuth({provider:'discord',options:{redirectTo}});if(error)$('#loginError').textContent=error.message;});
$('#logoutBtn').addEventListener('click',async()=>{await sb.auth.signOut();location.reload();});
$('#pendingLogoutBtn').addEventListener('click',async()=>{await sb.auth.signOut();location.reload();});
$('#modalClose').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal();});
$$('.nav-item').forEach(btn=>btn.addEventListener('click',async()=>{if(btn.classList.contains('hidden'))return;if(SYSTEM_PAGES.has(btn.dataset.page)&&!ownerOnly()){toast('Owner / Executive access only');return;}$$('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.page=btn.dataset.page;await render();}));
let searchTimer;$('#globalSearch').addEventListener('input',e=>{clearTimeout(searchTimer);const q=e.target.value.trim();if(q.length<2)return;searchTimer=setTimeout(()=>globalSearch(q),350);});
window.goPage=p=>{const b=$(`.nav-item[data-page="${p}"]`);if(b)b.click();};
window.copyText=async t=>{await navigator.clipboard.writeText(t);toast('Copied');};
window.deleteRow=async(t,id)=>{if(!canDelete())return toast('Owner / Executive delete permission required');if(!confirm('Delete this record?'))return;const {error}=await sb.from(t).delete().eq('id',id);if(error)return toast(error.message);await audit('delete',t,id,{});toast('Deleted');render();};

const ACTIVITY_TYPES={business:{table:'businesses',label:'Business',nameField:'name'},faction:{table:'factions',label:'Faction',nameField:'name'},housing:{table:'housing',label:'Housing',nameField:'discord_name'},one_of_one:{table:'one_of_ones',label:'1 of 1',nameField:'discord_name'}};
function activityMeta(r){const s=String(r?.status||'Active').toLowerCase();if(['inactive','closed'].includes(s))return{due:false,text:'Inactive',cls:''};if(!r?.next_activity_check)return{due:true,text:'Check Due',cls:'warn'};const due=new Date(`${dateOnly(r.next_activity_check)}T00:00:00`);const now=new Date();now.setHours(0,0,0,0);const days=Math.ceil((due-now)/86400000);if(days<0)return{due:true,text:`Overdue ${Math.abs(days)}d`,cls:'danger'};if(days===0)return{due:true,text:'Due Today',cls:'warn'};if(days<=7)return{due:false,text:`Due in ${days}d`,cls:'warn'};return{due:false,text:`Due in ${days}d`,cls:'blue'};}
function activityBadge(r){const m=activityMeta(r);return badge(m.text,m.cls);}
window.activityCheckForm=async(type,id)=>{
  const c=ACTIVITY_TYPES[type];if(!c)return;const {data:r,error}=await sb.from(c.table).select('*').eq('id',id).single();if(error||!r)return toast(error?.message||'Record not found');
  const name=type==='housing'?`${r.discord_name||r.owner_name||'Housing'}${r.postal?` • Postal ${r.postal}`:''}`:type==='one_of_one'?`${r.discord_name||'1 of 1'}${r.spawn_code?` • ${r.spawn_code}`:''}`:(r[c.nameField]||c.label);
  openModal(`<h3>30-Day Activity Check</h3><p class="muted"><b>${esc(c.label)}:</b> ${esc(name)}. The next review is scheduled automatically 30 days after this check.</p><form id="activityForm" class="form-grid">${field('Date Checked','check_date',today(),true,'date')}${type==='business'?field('Total Hours Worked','total_hours_worked',r.total_hours_worked||0,true,'number','0.1'):''}${selectField('Status','status',['Active','Review','Inactive'],r.status||'Active')}${area('Notes','notes','')}<div class="full"><button class="btn primary">Complete Check</button></div></form>`);
  $('#activityForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);const next=o.status==='Inactive'?null:addDaysIso(o.check_date,30);const update={status:o.status,last_activity_check:o.check_date,next_activity_check:next};if(type==='business')update.total_hours_worked=Number(o.total_hours_worked||0);const {error:ue}=await sb.from(c.table).update(update).eq('id',id);if(ue)return toast(ue.message);const {error:he}=await sb.from('activity_check_history').insert({entity_type:type,entity_id:id,entity_name:name,check_date:o.check_date,status:o.status,notes:o.notes||null,total_hours_worked:type==='business'?Number(o.total_hours_worked||0):null,checked_by:state.user.id});if(he)return toast(he.message);await audit('activity_check',type,id,{name,check_date:o.check_date,status:o.status,total_hours_worked:type==='business'?Number(o.total_hours_worked||0):undefined});closeModal();toast('Activity check completed');render();};
};
window.activityHistory=async(type,id)=>{const {data=[],error}=await sb.from('activity_check_history').select('*').eq('entity_type',type).eq('entity_id',id).order('check_date',{ascending:false});if(error)return toast(error.message);openModal(`<h3>Activity Check History</h3>${table(type==='business'?['Date Checked','Total Hours','Status','Notes']:['Date Checked','Status','Notes'],data.map(r=>type==='business'?[dateOnly(r.check_date),Number(r.total_hours_worked||0).toFixed(1),badge(r.status,r.status==='Inactive'?'danger':r.status==='Review'?'warn':''),esc(r.notes||'—')]:[dateOnly(r.check_date),badge(r.status,r.status==='Inactive'?'danger':r.status==='Review'?'warn':''),esc(r.notes||'—')]))}`);};

async function render(){
  if(SYSTEM_PAGES.has(state.page)&&!ownerOnly()){state.page='dashboard';$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page==='dashboard'));toast('Owner / Executive access only');}
  const pages={dashboard:renderDashboard,todo:renderTodos,businesses:renderBusinesses,oneofones:renderOneOfOnes,coins:renderCoinCollection,housing:renderHousing,factions:renderFactions,training:renderTraining,bans:renderBans,spawncodes:renderSpawnCodes,tcodes:renderTCodes,f9:renderF9,staff:renderStaff,backup:renderBackup,users:renderUsers,audit:renderAudit,settings:renderSettings};
  await (pages[state.page]||renderDashboard)();
}

async function getDueChecks(){
  const [{data:b=[]},{data:f=[]},{data:h=[]},{data:o=[]}]=await Promise.all([
    sb.from('businesses').select('id,name,status,last_activity_check,next_activity_check,total_hours_worked'),
    sb.from('factions').select('id,name,status,last_activity_check,next_activity_check'),
    sb.from('housing').select('id,discord_name,owner_name,postal,status,last_activity_check,next_activity_check'),
    sb.from('one_of_ones').select('id,discord_name,spawn_code,status,last_activity_check,next_activity_check')
  ]);
  const out=[];const add=(type,r,name)=>{const m=activityMeta(r);if(m.due)out.push({type,id:r.id,name,due:r.next_activity_check,last:r.last_activity_check,meta:m});};
  b.forEach(r=>add('business',r,r.name));f.forEach(r=>add('faction',r,r.name));h.forEach(r=>add('housing',r,`${r.discord_name||r.owner_name||'Housing'}${r.postal?` • ${r.postal}`:''}`));o.forEach(r=>add('one_of_one',r,`${r.discord_name} • ${r.spawn_code}`));
  return out.sort((a,b)=>String(a.due||'').localeCompare(String(b.due||'')));
}
function auditTitle(r){const d=r.details||{};if(r.action==='activity_check')return `Activity check completed${d.name?`: ${d.name}`:''}`;if(r.action==='create')return `Added ${String(r.entity_type||'record').replaceAll('_',' ')}`;if(r.action==='update')return `Updated ${String(r.entity_type||'record').replaceAll('_',' ')}`;if(r.action==='delete')return `Deleted ${String(r.entity_type||'record').replaceAll('_',' ')}`;if(r.action==='import')return `Imported ${String(r.entity_type||'records').replaceAll('_',' ')}${d.rows?` (${d.rows})`:''}`;if(r.action==='approve')return 'Approved Command Center user';return `${String(r.action||'Activity').replaceAll('_',' ')} • ${String(r.entity_type||'record').replaceAll('_',' ')}`;}

async function renderDashboard(){
  setHead('Dashboard','New Horizons Role Play management overview');
  const since7=new Date(Date.now()-7*86400000).toISOString().slice(0,10);
  const [activeStaff,trainings,housing,ones,bans,openTasks,businesses,factions,spawnCodes,tCodes,f9Items,coinOpen,due] = await Promise.all([
    count('staff',q=>q.eq('status','Active')),
    count('staff_training',q=>q.gte('training_date',since7)),
    count('housing'),
    count('one_of_ones'),
    count('bans'),
    count('admin_todos',q=>q.not('status','in','("Done","Completed")')),
    count('businesses'),
    count('factions'),
    count('spawn_codes'),
    count('t_codes'),
    count('f9_items'),
    count('coin_collections',q=>q.eq('collected',false)),
    getDueChecks()
  ]);

  let recent=[];
  if(ownerOnly()){
    const [{data:logs=[]},{data:profiles=[]}]=await Promise.all([
      sb.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(40),
      sb.from('profiles').select('id,display_name,discord_name')
    ]);
    const names=Object.fromEntries(profiles.map(p=>[p.id,p.display_name||p.discord_name||'Staff']));
    recent=logs.map(r=>({title:auditTitle(r),sub:`${names[r.user_id]||'Staff'} • ${datefmt(r.created_at)}`}));
  }else{
    const {data:hist=[]}=await sb.from('activity_check_history').select('*').order('created_at',{ascending:false}).limit(30);
    recent=hist.map(r=>({title:`${r.entity_name||r.entity_type} activity check`,sub:`${r.status} • ${datefmt(r.created_at)}`}));
  }

  const {data:tasks=[]}=await sb.from('admin_todos').select('*').not('status','in','("Done","Completed")').order('due_date',{ascending:true}).limit(6);
  const {data:recentBans=[]}=await sb.from('bans').select('*').order('ban_date',{ascending:false}).order('created_at',{ascending:false}).limit(6);

  $('#content').innerHTML=`
    <div class="panel"><div class="panel-head"><div><div class="panel-kicker">NHRP // OPERATIONS HUB</div><h2>Welcome back, ${esc(state.profile.display_name||state.profile.discord_name||'Staff')}</h2><div class="small-note">New Horizons Role Play management command center</div></div><div class="online-pill"><span></span> SYSTEM ONLINE</div></div></div>

    <div class="panel"><div class="panel-head"><div><div class="panel-kicker">OVERVIEW</div><h2>Server Operations</h2></div><div class="small-note">NHRP-OPS</div></div><div class="stats-grid">
      ${stat('👥','ACTIVE STAFF',activeStaff,'Staff Management')}
      ${stat('🎓','TRAININGS',trainings,'Last 7 Days')}
      ${stat('🏢','BUSINESSES',businesses,'Tracked')}
      ${stat('◆','1 OF 1',ones,'Registered')}
      ${stat('🏠','HOUSING',housing,'Records')}
      ${stat('⚑','FACTIONS',factions,'Tracked')}
      ${stat('⌘','SPAWN CODES',spawnCodes,'Records')}
      ${stat('T','T/CODES',tCodes,'Quick Reference')}
      ${stat('🪙','F9 ITEMS',f9Items,'Coin Shop')}
      ${stat('✓','COIN COLLECTION',coinOpen,'Outstanding')}
      ${stat('🔨','BAN LOGS',bans,'Total Records')}
      ${stat('📋','OPEN TASKS',openTasks,'Require Action')}
      ${stat('⏱','CHECKS DUE',due.length,'30-Day Reviews')}
    </div></div>

    <div class="dashboard-grid">
      <div class="panel dash-panel"><div class="panel-head"><div><div class="panel-kicker">LIVE FEED</div><h2>Recent Activity</h2></div>${badge('LIVE')}</div><div class="dash-list">
        ${due.length?due.slice(0,12).map(x=>`<div class="dash-row required-row"><div><div class="kicker-warning">ACTIVITY CHECK ${esc(x.meta.text.toUpperCase())}</div><b>${esc(ACTIVITY_TYPES[x.type].label)}: ${esc(x.name)}</b><small>Last checked: ${dateOnly(x.last)}</small></div><button class="btn secondary small" onclick="activityCheckForm('${x.type}','${x.id}')">Complete</button></div>`).join(''):''}
        ${recent.length?recent.slice(0,12).map(x=>`<div class="dash-row"><div><b>${esc(x.title)}</b><small>${esc(x.sub)}</small></div></div>`).join(''):(due.length?'':'<div class="empty">No recent activity.</div>')}
      </div></div>

      <div class="panel dash-panel"><div class="panel-head"><div><div class="panel-kicker">ACTION QUEUE</div><h2>Pending Tasks</h2></div>${badge(tasks.length)}</div><div class="dash-list">${tasks.length?tasks.map(t=>`<div class="dash-row"><div><b>${esc(t.title)}</b><small>${esc(t.assigned_to||'Unassigned')} • Due ${dateOnly(t.due_date)}</small>${t.screenshot_url?`<small>📎 Screenshot attached</small>`:''}</div>${badge(t.priority,t.priority==='Urgent'||t.priority==='High'?'danger':'')}</div>`).join(''):'<div class="empty">No pending tasks.</div>'}</div><button class="btn secondary wide" onclick="goPage('todo')">VIEW ALL TASKS →</button></div>

      <div class="panel dash-panel"><div class="panel-head"><div><div class="panel-kicker">SECURITY</div><h2>Recent Bans</h2></div></div><div class="dash-list">${recentBans.length?recentBans.map(b=>`<div class="dash-row"><div><b>${esc(b.player_name)}</b><small>${esc(b.reason)} • ${dateOnly(b.ban_date)}</small></div></div>`).join(''):'<div class="empty">No ban records.</div>'}</div><button class="btn secondary wide" onclick="goPage('bans')">VIEW BAN LOGS →</button></div>
    </div>

    <div class="panel"><div class="panel-head"><div><div class="panel-kicker">COMMANDS</div><h2>Quick Actions</h2></div></div><div class="quick-grid">
      <button class="quick-btn" onclick="goPage('oneofones')"><span>◆</span>Add-Ins</button>
      <button class="quick-btn" onclick="goPage('businesses')"><span>🏢</span>Businesses</button>
      <button class="quick-btn" onclick="goPage('housing')"><span>🏠</span>Housing</button>
      <button class="quick-btn" onclick="goPage('factions')"><span>⚑</span>Factions</button>
      <button class="quick-btn" onclick="goPage('bans')"><span>🔨</span>Ban Logs</button>
      <button class="quick-btn" onclick="goPage('spawncodes')"><span>⌘</span>Spawn Codes</button>
      <button class="quick-btn" onclick="goPage('tcodes')"><span>T</span>T/Codes</button>
      <button class="quick-btn" onclick="goPage('f9')"><span>🪙</span>F9</button>
      <button class="quick-btn" onclick="goPage('coins')"><span>✓</span>Coin Collection</button>
      <button class="quick-btn" onclick="goPage('training')"><span>🎓</span>Staff Training</button>
      <button class="quick-btn" onclick="goPage('todo')"><span>✓</span>Admin To-Do</button>
    </div></div>`;
}

async function renderTodos(){
  setHead('Admin To-Do','Manage administrative tasks, priorities, assignments, and screenshots');const {data=[]}=await sb.from('admin_todos').select('*').order('due_date',{ascending:true});
  const cols=[['To Do',['Open','To Do']],['In Progress',['In Progress']],['Done',['Done','Completed']]];
  $('#content').innerHTML=panel('Admin To-Do','OPERATIONS',`<div class="toolbar" style="margin-bottom:14px">${canWrite()?'<button class="btn primary" onclick="todoForm()">+ Add Task</button>':''}<input id="todoSearch" class="input" placeholder="Search tasks..."></div><div class="todo-grid">${cols.map(([label,statuses])=>{const rows=data.filter(r=>statuses.includes(r.status||'Open'));return `<div class="todo-column"><h3>${label}<span class="todo-count">${rows.length}</span></h3>${rows.length?rows.map(t=>`<div class="task-card"><h4>${esc(t.title)}</h4><div class="task-meta">Assigned: ${esc(t.assigned_to||'Unassigned')}<br>Due: ${dateOnly(t.due_date)}<br>Priority: <span class="priority-${String(t.priority||'Normal').toLowerCase()}">${esc(t.priority||'Normal')}</span>${t.notes?`<br>${esc(t.notes)}`:''}${t.screenshot_url?`<br>Screenshot: ${screenshotLink(t.screenshot_url,'Open')}`:''}</div><div class="task-actions">${canWrite()?`<button class="btn secondary small" onclick="todoForm('${t.id}')">Edit</button>${label!=='Done'?`<button class="btn primary small" onclick="setTaskStatus('${t.id}','${label==='To Do'?'In Progress':'Done'}')">${label==='To Do'?'Start':'Complete'}</button>`:''}${canDelete()?`<button class="btn danger small" onclick="deleteRow('admin_todos','${t.id}')">Delete</button>`:''}`:''}</div></div>`).join(''):'<div class="empty">No tasks.</div>'}</div>`;}).join('')}</div>`);
  $('#todoSearch').oninput=e=>{const q=e.target.value.toLowerCase();$$('.task-card').forEach(c=>c.style.display=c.textContent.toLowerCase().includes(q)?'':'none');};
}
window.todoForm=async id=>{let r={status:'To Do',priority:'Normal'};if(id){const {data}=await sb.from('admin_todos').select('*').eq('id',id).single();r=data||r;}openModal(`<h3>${id?'Edit':'Add'} Task</h3><form id="todoForm" class="form-grid">${field('Task','title',r.title,true)}${field('Assigned To','assigned_to',r.assigned_to)}${selectField('Priority','priority',['Low','Normal','High','Urgent'],r.priority||'Normal')}${selectField('Status','status',['To Do','In Progress','Done'],['Open'].includes(r.status)?'To Do':r.status)}${field('Due Date','due_date',dateOnly(r.due_date)==='—'?'':dateOnly(r.due_date),false,'date')}${area('Notes','notes',r.notes)}${screenshotDropField('todoScreenshot',r.screenshot_url)}<div class="full"><button class="btn primary">Save Task</button></div></form>`);initScreenshotDrop('todoScreenshot','admin-todo');$('#todoForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);const res=id?await sb.from('admin_todos').update(o).eq('id',id).select().single():await sb.from('admin_todos').insert({...o,server:'NHRP'}).select().single();if(res.error)return toast(res.error.message);await audit(id?'update':'create','admin_todos',res.data.id,{title:o.title});closeModal();toast('Task saved');renderTodos();};};
window.setTaskStatus=async(id,status)=>{const {error}=await sb.from('admin_todos').update({status}).eq('id',id);if(error)return toast(error.message);await audit('update','admin_todos',id,{status});renderTodos();};

async function renderBusinesses(){
  setHead('Business Owners','Manage NHRP business ownership records');const {data=[]}=await sb.from('businesses').select('*').order('name');const types=await getCategories('business_type','',data.map(r=>r.type).filter(Boolean));
  $('#content').innerHTML=panel('Business Owners','RECORDS',`<div class="table-controls"><div class="toolbar">${canWrite()?'<button class="btn primary" onclick="businessForm()">+ Add Business</button><button class="btn secondary" onclick="importCsvDialog(\'businesses\')">Import CSV</button>':''}<button class="btn secondary" onclick="exportBusinesses()">Export CSV</button>${categoryButton('business_type')}</div><div class="filter-row"><select id="bizType"><option value="">All Business Types</option>${types.map(x=>`<option>${esc(x)}</option>`).join('')}</select><input id="bizSearch" placeholder="Search business, Discord name, ID, job code..."></div></div><div id="businessTable"></div>`);
  const draw=()=>{const type=$('#bizType').value,q=$('#bizSearch').value.toLowerCase();const rows=data.filter(r=>(!type||r.type===type)&&(!q||[r.name,r.owner_name,r.owner_discord_id,r.job_code,r.postal].join(' ').toLowerCase().includes(q)));$('#businessTable').innerHTML=table(['Postal','Business Name','Business Type','Discord Name','Discord ID','Job Code','Purchase Date','Total Hours','Date Checked','Status','Screenshot','Actions'],rows.map(r=>[esc(r.postal),`<span class="clickable" onclick="businessDetail('${r.id}')">${esc(r.name)}</span>`,esc(r.type),esc(r.owner_name),code(r.owner_discord_id),code(r.job_code),dateOnly(r.purchase_date),Number(r.total_hours_worked||0).toFixed(1),dateOnly(r.last_activity_check),badge(r.status,r.status==='Inactive'||r.status==='Closed'?'danger':r.status==='Review'?'warn':''),screenshotLink(r.screenshot_url),standardActions('businesses',r.id,'businessForm')]))};$('#bizType').oninput=draw;$('#bizSearch').oninput=draw;draw();
}
window.businessForm=async id=>{let r={status:'Active',total_hours_worked:0,purchase_date:today()};if(id){const {data}=await sb.from('businesses').select('*').eq('id',id).single();r=data||r;}const types=await getCategories('business_type',r.type);openModal(`<h3>${id?'Edit':'Add'} Business</h3><form id="businessForm" class="form-grid">${field('Postal','postal',r.postal)}${field('Business Name','name',r.name,true)}${selectField('Business Type','type',types,r.type)}${field('Discord Name','owner_name',r.owner_name)}${field('Discord ID','owner_discord_id',r.owner_discord_id)}${field('Job Code','job_code',r.job_code)}${field('Purchase Date','purchase_date',dateOnly(r.purchase_date)==='—'?today():dateOnly(r.purchase_date),false,'date')}${field('Total Hours Worked','total_hours_worked',r.total_hours_worked,false,'number','0.1')}${field('Date Checked','last_activity_check',dateOnly(r.last_activity_check)==='—'?'':dateOnly(r.last_activity_check),false,'date')}${selectField('Status','status',['Active','Review','Inactive','Closed'],r.status||'Active')}${screenshotDropField('businessScreenshot',r.screenshot_url)}${area('Notes','notes',r.notes)}<div class="full"><button class="btn primary">Save Business</button></div></form>`);initScreenshotDrop('businessScreenshot','businesses');$('#businessForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);o.total_hours_worked=Number(o.total_hours_worked||0);o.server='NHRP';o.next_activity_check=(o.status==='Inactive'||o.status==='Closed'||!o.last_activity_check)?null:addDaysIso(o.last_activity_check,30);const res=id?await sb.from('businesses').update(o).eq('id',id).select().single():await sb.from('businesses').insert(o).select().single();if(res.error)return toast(res.error.message);await audit(id?'update':'create','business',res.data.id,{name:o.name});closeModal();toast('Business saved');renderBusinesses();};};
window.businessDetail=async id=>{const [{data:b},{data:p=[]}]=await Promise.all([sb.from('businesses').select('*').eq('id',id).single(),sb.from('payments').select('*').eq('business_id',id).order('payment_date',{ascending:false}).limit(15)]);if(!b)return;openModal(`<h3>${esc(b.name)}</h3><div class="detail-grid">${[['Postal',b.postal],['Business Type',b.type],['Discord Name',b.owner_name],['Discord ID',b.owner_discord_id],['Job Code',b.job_code],['Purchase Date',dateOnly(b.purchase_date)],['Total Hours Worked',Number(b.total_hours_worked||0).toFixed(1)],['Date Checked',dateOnly(b.last_activity_check)],['Status',b.status]].map(x=>`<div class="detail-box"><span>${esc(x[0])}</span><strong>${esc(x[1]||'—')}</strong></div>`).join('')}</div>${b.screenshot_url?`<div class="detail-screenshot"><img src="${esc(b.screenshot_url)}" alt="Business screenshot"><a class="btn secondary small" href="${esc(b.screenshot_url)}" target="_blank" rel="noopener">Open Screenshot</a></div>`:''}<h3>Recent Payments</h3>${table(['Date','Name','Category','Amount'],p.map(x=>[dateOnly(x.payment_date),esc(x.discord_name||x.payer_name),esc(x.category),`$${money(x.amount)}`]))}`);};
window.exportBusinesses=async()=>{const {data=[]}=await sb.from('businesses').select('*').order('name');downloadCsv('nhrp_businesses.csv',['Postal','Business Name','Business Type','Discord Name','Discord ID','Job Code','Purchase Date','Total Hours Worked','Date Checked','Status','Notes','Screenshot'],data.map(r=>[r.postal,r.name,r.type,r.owner_name,r.owner_discord_id,r.job_code,r.purchase_date,r.total_hours_worked,r.last_activity_check,r.status,r.notes,r.screenshot_url]));};

async function renderOneOfOnes(){
  setHead('Add-Ins','Manage add-ins, payment details, screenshots, and 30-day activity checks in one record');
  const {data=[]}=await sb.from('one_of_ones').select('*').order('add_date',{ascending:false});
  const oneTypes=await getCategories('one_type','',data.map(r=>r.type).filter(Boolean));
  const body=`<div class="toolbar">${canWrite()?'<button class="btn primary" onclick="oneForm()">+ Add Record</button><button class="btn secondary" onclick="importCsvDialog(\'one_of_ones\')">Import CSV</button>':''}<button class="btn secondary" onclick="exportOneOfOnes()">Export CSV</button><button class="btn secondary" onclick="downloadTemplate(\'one_of_ones\')">CSV Template</button>${categoryButton('one_type')}<input id="oneSearch" placeholder="Search name, ID, spawn code, payment method, notes..."></div><div class="activity-banner">Add-In Activity Check: Every 30 days</div><div class="subtabs">${['All',...oneTypes].map(t=>`<button class="subtab ${state.oneType===t?'active':''}" onclick="setOneType('${t.replaceAll("'","\\'")}')">${esc(t)}</button>`).join('')}</div><div id="oneTable"></div>`;
  $('#content').innerHTML=panel('Add-Ins','RECORDS',body);
  const draw=()=>{const q=$('#oneSearch').value.toLowerCase();const rows=data.filter(r=>(state.oneType==='All'||r.type===state.oneType)&&(!q||[r.discord_name,r.discord_id,r.spawn_code,r.type,r.payment_method,r.amount,r.notes].join(' ').toLowerCase().includes(q)));$('#oneTable').innerHTML=table(['Discord Name','Discord ID','Type','Spawn Code','Date','Payment Method','Amount','Date Checked','Status','Notes','Screenshot','Activity','Actions'],rows.map(r=>[esc(r.discord_name),code(r.discord_id),esc(r.type),code(r.spawn_code),dateOnly(r.add_date),esc(r.payment_method||'—'),r.amount==null?'—':`$${money(r.amount)}`,dateOnly(r.last_activity_check),badge(r.status,r.status==='Inactive'?'danger':r.status==='Review'?'warn':''),esc(r.notes||'—'),screenshotLink(r.screenshot_url),activityBadge(r),`<div class="actions">${canWrite()?`<button class="btn primary small" onclick="activityCheckForm('one_of_one','${r.id}')">Check</button>`:''}<button class="btn secondary small" onclick="activityHistory('one_of_one','${r.id}')">History</button>${standardActions('one_of_ones',r.id,'oneForm')}</div>`]))};$('#oneSearch').oninput=draw;draw();
}
window.setOneType=t=>{state.oneType=t;renderOneOfOnes();};
window.oneForm=async id=>{let r={status:'Active',add_date:today(),type:'Vehicles',amount:0,payment_method:'',last_activity_check:null,notes:''};if(id){const {data}=await sb.from('one_of_ones').select('*').eq('id',id).single();r=data||r;}const oneTypes=await getCategories('one_type',r.type);openModal(`<h3>${id?'Edit':'Add'} Add-In</h3><form id="oneForm" class="form-grid">${field('Discord Name','discord_name',r.discord_name,true)}${field('Discord ID','discord_id',r.discord_id,true)}${selectField('Type','type',oneTypes,r.type||'Vehicles')}${field('Spawn Code','spawn_code',r.spawn_code,true)}${field('Date','add_date',dateOnly(r.add_date)==='—'?today():dateOnly(r.add_date),true,'date')}${field('Payment Method','payment_method',r.payment_method||'')}${field('Amount','amount',r.amount??0,false,'number','0.01')}${field('Activity Check Date','last_activity_check',dateOnly(r.last_activity_check)==='—'?'':dateOnly(r.last_activity_check),false,'date')}${selectField('Status','status',['Active','Review','Inactive'],r.status||'Active')}${area('Notes','notes',r.notes)}${screenshotDropField('oneScreenshot',r.screenshot_url)}<div class="full"><button class="btn primary">Save Add-In</button></div></form>`);initScreenshotDrop('oneScreenshot','one-of-one');$('#oneForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);o.amount=o.amount==null?0:Number(o.amount||0);const checked=normalizeDate(o.last_activity_check,null);o.last_activity_check=checked;o.next_activity_check=o.status==='Inactive'?null:(checked?addDaysIso(checked,30):(r.next_activity_check||addDaysIso(o.add_date||today(),30)));const res=id?await sb.from('one_of_ones').update(o).eq('id',id).select().single():await sb.from('one_of_ones').insert(o).select().single();if(res.error)return toast(res.error.message);await audit(id?'update':'create','one_of_one',res.data.id,{spawn_code:o.spawn_code,payment_method:o.payment_method,amount:o.amount,last_activity_check:o.last_activity_check});closeModal();toast('Add-In saved');renderOneOfOnes();};};
window.exportOneOfOnes=async()=>{const {data=[]}=await sb.from('one_of_ones').select('*').order('add_date',{ascending:false});downloadCsv('nhrp_add_ins.csv',['Discord Name','Discord ID','Type','Spawn Code','Date','Payment Method','Amount','Date Checked','Status','Notes','Screenshot'],data.map(r=>[r.discord_name,r.discord_id,r.type,r.spawn_code,r.add_date,r.payment_method,r.amount,r.last_activity_check,r.status,r.notes,r.screenshot_url]));};



async function renderCoinCollection(){
  setHead('Coin Collection','Track coin balances and mark each account collected');
  const {data=[]}=await sb.from('coin_collections').select('*').order('total_coins',{ascending:false}).order('username');
  const totalCoins=data.reduce((s,r)=>s+Number(r.total_coins||0),0);
  const collected=data.filter(r=>r.collected);
  const collectedCoins=collected.reduce((s,r)=>s+Number(r.total_coins||0),0);
  const outstandingCoins=totalCoins-collectedCoins;
  const body=`<div class="stats-grid coin-stats">
      ${stat('👤','ACCOUNTS',data.length,'Total')}
      ${stat('🪙','TOTAL COINS',totalCoins.toLocaleString(),'All Accounts')}
      ${stat('✓','COLLECTED',collected.length,`${collectedCoins.toLocaleString()} Coins`)}
      ${stat('○','OUTSTANDING',data.length-collected.length,`${outstandingCoins.toLocaleString()} Coins`)}
    </div>
    <div class="table-controls"><div class="toolbar">${canWrite()?'<button class="btn secondary" onclick="importCsvDialog(\'coin_collections\')">Import CSV</button>':''}<button class="btn secondary" onclick="exportCoinCollection()">Export CSV</button><button class="btn secondary" onclick="downloadTemplate(\'coin_collections\')">CSV Template</button></div>
    <div class="filter-row"><select id="coinStatus"><option value="outstanding" ${state.coinFilter==='outstanding'?'selected':''}>Outstanding</option><option value="collected" ${state.coinFilter==='collected'?'selected':''}>Collected</option><option value="all" ${state.coinFilter==='all'?'selected':''}>All</option></select><input id="coinSearch" placeholder="Search username..."></div></div>
    <div id="coinTable"></div>`;
  $('#content').innerHTML=panel('Coin Collection','RECORDS',body);
  const draw=()=>{const q=$('#coinSearch').value.toLowerCase();const filter=$('#coinStatus').value;state.coinFilter=filter;const rows=data.filter(r=>(filter==='all'||(filter==='collected'?r.collected:!r.collected))&&(!q||String(r.username||'').toLowerCase().includes(q)));$('#coinTable').innerHTML=table(['Username','Total Coins','Collected'],rows.map(r=>[esc(r.username),Number(r.total_coins||0).toLocaleString(),`<label class="coin-check"><input type="checkbox" ${r.collected?'checked':''} ${canWrite()?'':'disabled'} onchange="toggleCoinCollected('${r.id}',this.checked)"><span>${r.collected?'Collected':'Outstanding'}</span></label>`]))};$('#coinSearch').oninput=draw;$('#coinStatus').onchange=draw;draw();
}
window.toggleCoinCollected=async(id,checked)=>{if(!canWrite())return toast('Write permission required');const update={collected:!!checked,collected_at:checked?new Date().toISOString():null,collected_by:checked?state.user.id:null};const {error}=await sb.from('coin_collections').update(update).eq('id',id);if(error)return toast(error.message);await audit('update','coin_collection',id,{collected:!!checked});toast(checked?'Marked collected':'Marked outstanding');renderCoinCollection();};
window.exportCoinCollection=async()=>{const {data=[]}=await sb.from('coin_collections').select('*').order('total_coins',{ascending:false}).order('username');downloadCsv('nhrp_coin_collection.csv',['Username','Total Coins','Collected'],data.map(r=>[r.username,r.total_coins,r.collected?'Yes':'No']));};

async function renderHousing(){
  setHead('Housing','Manage housing records and 30-day activity checks');const {data=[]}=await sb.from('housing').select('*').order('created_at',{ascending:false});const tiers=await getCategories('housing_tier','',data.map(r=>r.housing_tier).filter(Boolean));
  $('#content').innerHTML=panel('Housing','RECORDS',`<div class="toolbar">${canWrite()?'<button class="btn primary" onclick="housingForm()">+ Add Housing</button><button class="btn secondary" onclick="importCsvDialog(\'housing\')">Import CSV</button>':''}<button class="btn secondary" onclick="exportHousing()">Export CSV</button><button class="btn secondary" onclick="downloadTemplate(\'housing\')">CSV Template</button>${categoryButton('housing_tier')}<select id="housingTierFilter"><option value="All">All Tiers</option>${tiers.map(t=>`<option value="${esc(t)}" ${state.housingTier===t?'selected':''}>${esc(t)}</option>`).join('')}</select><input id="housingSearch" placeholder="Search name, Discord ID, postal..."></div><div class="activity-banner">Housing Activity Check: Every 30 days</div><div id="housingTable"></div>`);
  const draw=()=>{const q=$('#housingSearch').value.toLowerCase();const rows=data.filter(r=>(state.housingTier==='All'||r.housing_tier===state.housingTier)&&(!q||[r.discord_name,r.owner_name,r.discord_id,r.housing_tier,r.postal,r.price].join(' ').toLowerCase().includes(q)));$('#housingTable').innerHTML=table(['Discord Name','Discord ID','Housing Tier','Postal','Price','Date Added','Date Checked','Status','Screenshot','Activity','Actions'],rows.map(r=>[esc(r.discord_name||r.owner_name),code(r.discord_id),esc(r.housing_tier),esc(r.postal),r.price==null?'—':`$${money(r.price)}`,dateOnly(r.add_date||r.created_at),dateOnly(r.last_activity_check),badge(r.status,r.status==='Inactive'?'danger':r.status==='Review'?'warn':''),screenshotLink(r.screenshot_url),activityBadge(r),`<div class="actions">${canWrite()?`<button class="btn primary small" onclick="activityCheckForm('housing','${r.id}')">Check</button>`:''}<button class="btn secondary small" onclick="activityHistory('housing','${r.id}')">History</button>${standardActions('housing',r.id,'housingForm')}</div>`]))};$('#housingSearch').oninput=draw;$('#housingTierFilter').onchange=e=>{state.housingTier=e.target.value;draw();};draw();
}
window.housingForm=async id=>{let r={status:'Active',add_date:today(),housing_tier:'Tier 1',price:null,screenshot_url:''};if(id){const {data}=await sb.from('housing').select('*').eq('id',id).single();r=data||r;}const tiers=await getCategories('housing_tier',r.housing_tier);openModal(`<h3>${id?'Edit':'Add'} Housing</h3><form id="housingForm" class="form-grid">${field('Discord Name','discord_name',r.discord_name||r.owner_name,true)}${field('Discord ID','discord_id',r.discord_id,true)}${selectField('Housing Tier','housing_tier',tiers,r.housing_tier||'Tier 1')}${field('Postal','postal',r.postal)}${field('Price','price',r.price??'',false,'number','0.01')}${field('Date Added','add_date',dateOnly(r.add_date||r.created_at)==='—'?today():dateOnly(r.add_date||r.created_at),true,'date')}${selectField('Status','status',['Active','Review','Inactive'],r.status||'Active')}${screenshotDropField('housingScreenshot',r.screenshot_url)}<div class="full"><button class="btn primary">Save Housing</button></div></form>`);initScreenshotDrop('housingScreenshot','housing');$('#housingForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);o.owner_name=o.discord_name;o.price=o.price==null?null:Number(o.price);o.server='NHRP';if(!id)o.next_activity_check=addDaysIso(o.add_date||today(),30);const res=id?await sb.from('housing').update(o).eq('id',id).select().single():await sb.from('housing').insert(o).select().single();if(res.error)return toast(res.error.message);await audit(id?'update':'create','housing',res.data.id,{name:o.discord_name,postal:o.postal,price:o.price});closeModal();toast('Housing saved');renderHousing();};};
window.exportHousing=async()=>{const {data=[]}=await sb.from('housing').select('*').order('created_at',{ascending:false});downloadCsv('nhrp_housing.csv',['Discord Name','Discord ID','Housing Tier','Postal','Price','Date Added','Date Checked','Status','Screenshot'],data.map(r=>[r.discord_name||r.owner_name,r.discord_id,r.housing_tier,r.postal,r.price,r.add_date||dateOnly(r.created_at),r.last_activity_check,r.status,r.screenshot_url]));};

async function renderFactions(){
  setHead('Factions','Manage faction leadership and 30-day activity checks');const {data=[]}=await sb.from('factions').select('*').order('name');const types=await getCategories('faction_type','',data.map(r=>r.type).filter(Boolean));
  $('#content').innerHTML=panel('Factions','RECORDS',`<div class="toolbar">${canWrite()?'<button class="btn primary" onclick="factionForm()">+ Add Faction</button><button class="btn secondary" onclick="importCsvDialog(\'factions\')">Import CSV</button>':''}<button class="btn secondary" onclick="exportFactions()">Export CSV</button><button class="btn secondary" onclick="downloadTemplate('factions')">CSV Template</button>${categoryButton('faction_type')}<select id="factionType"><option value="">All Categories</option>${types.map(x=>`<option>${esc(x)}</option>`).join('')}</select><input id="factionSearch" placeholder="Search faction, leader, type..."></div><div class="activity-banner">Faction Activity Check: Every 30 days</div><div id="factionTable"></div>`);
  const draw=()=>{const q=$('#factionSearch').value.toLowerCase(),type=$('#factionType').value;const rows=data.filter(r=>(!type||r.type===type)&&(!q||[r.name,r.type,r.leader_name,r.leader_discord_id].join(' ').toLowerCase().includes(q)));$('#factionTable').innerHTML=table(['Faction','Type','Leader / Discord Name','Discord ID','Date Checked','Status','Screenshot','Activity','Actions'],rows.map(r=>[esc(r.name),esc(r.type),esc(r.leader_name),code(r.leader_discord_id),dateOnly(r.last_activity_check),badge(r.status,r.status==='Inactive'?'danger':r.status==='Review'?'warn':''),screenshotLink(r.screenshot_url),activityBadge(r),`<div class="actions">${canWrite()?`<button class="btn primary small" onclick="activityCheckForm('faction','${r.id}')">Check</button>`:''}<button class="btn secondary small" onclick="activityHistory('faction','${r.id}')">History</button>${standardActions('factions',r.id,'factionForm')}</div>`]))};$('#factionSearch').oninput=draw;$('#factionType').onchange=draw;draw();
}
window.factionForm=async id=>{let r={status:'Active',screenshot_url:''};if(id){const {data}=await sb.from('factions').select('*').eq('id',id).single();r=data||r;}const types=await getCategories('faction_type',r.type);openModal(`<h3>${id?'Edit':'Add'} Faction</h3><form id="factionForm" class="form-grid">${field('Faction Name','name',r.name,true)}${selectField('Type','type',types,r.type)}${field('Leader / Discord Name','leader_name',r.leader_name)}${field('Leader Discord ID','leader_discord_id',r.leader_discord_id)}${selectField('Status','status',['Active','Review','Inactive','Closed'],r.status||'Active')}${area('Notes','notes',r.notes)}${screenshotDropField('factionScreenshot',r.screenshot_url)}<div class="full"><button class="btn primary">Save Faction</button></div></form>`);initScreenshotDrop('factionScreenshot','factions');$('#factionForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);o.server='NHRP';if(!id)o.next_activity_check=addDaysIso(today(),30);const res=id?await sb.from('factions').update(o).eq('id',id).select().single():await sb.from('factions').insert(o).select().single();if(res.error)return toast(res.error.message);await audit(id?'update':'create','faction',res.data.id,{name:o.name});closeModal();toast('Faction saved');renderFactions();};};
window.exportFactions=async()=>{const {data=[]}=await sb.from('factions').select('*').order('name');downloadCsv('nhrp_factions.csv',['Faction Name','Type','Leader Discord Name','Leader Discord ID','Date Checked','Status','Notes','Screenshot'],data.map(r=>[r.name,r.type,r.leader_name,r.leader_discord_id,r.last_activity_check,r.status,r.notes,r.screenshot_url]));};

async function renderTraining(){
  setHead('Staff Training','Track staff training records');const {data=[]}=await sb.from('staff_training').select('*').order('training_date',{ascending:false});const trainings=await getCategories('training_name','',data.map(r=>r.training_name).filter(Boolean));
  $('#content').innerHTML=panel('Staff Training','SERVER',`<div class="toolbar">${canWrite()?'<button class="btn primary" onclick="trainingForm()">+ Add Training</button><button class="btn secondary" onclick="importCsvDialog(\'staff_training\')">Import CSV</button>':''}<button class="btn secondary" onclick="exportTraining()">Export CSV</button>${categoryButton('training_name')}<select id="trainingCategory"><option value="">All Training Categories</option>${trainings.map(x=>`<option>${esc(x)}</option>`).join('')}</select><input id="trainingSearch" placeholder="Search staff, Discord ID, training, trainer..."></div><div id="trainingTable"></div>`);
  const draw=()=>{const q=$('#trainingSearch').value.toLowerCase(),cat=$('#trainingCategory').value;const rows=data.filter(r=>(!cat||r.training_name===cat)&&(!q||[r.staff_name,r.discord_name,r.discord_id,r.training_name,r.trainer_name].join(' ').toLowerCase().includes(q)));$('#trainingTable').innerHTML=table(['Staff Name','Discord Name','Discord ID','Training','Trainer','Date','Notes','Actions'],rows.map(r=>[esc(r.staff_name),esc(r.discord_name),code(r.discord_id),esc(r.training_name),esc(r.trainer_name),dateOnly(r.training_date),esc(r.notes||'—'),standardActions('staff_training',r.id,'trainingForm')]))};$('#trainingSearch').oninput=draw;$('#trainingCategory').onchange=draw;draw();
}
window.trainingForm=async id=>{let r={training_date:today()};if(id){const {data}=await sb.from('staff_training').select('*').eq('id',id).single();r=data||r;}const trainings=await getCategories('training_name',r.training_name);openModal(`<h3>${id?'Edit':'Add'} Training</h3><form id="trainingForm" class="form-grid">${field('Staff Name','staff_name',r.staff_name,true)}${field('Discord Name','discord_name',r.discord_name)}${field('Discord ID','discord_id',r.discord_id)}${selectField('Training','training_name',trainings,r.training_name)}${field('Trainer','trainer_name',r.trainer_name)}${field('Training Date','training_date',dateOnly(r.training_date)==='—'?today():dateOnly(r.training_date),true,'date')}${area('Notes','notes',r.notes)}<div class="full"><button class="btn primary">Save Training</button></div></form>`);$('#trainingForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);const res=id?await sb.from('staff_training').update(o).eq('id',id).select().single():await sb.from('staff_training').insert(o).select().single();if(res.error)return toast(res.error.message);await audit(id?'update':'create','staff_training',res.data.id,{training:o.training_name,name:o.staff_name});closeModal();toast('Training saved');renderTraining();};};
window.exportTraining=async()=>{const {data=[]}=await sb.from('staff_training').select('*').order('training_date',{ascending:false});downloadCsv('nhrp_staff_training.csv',['Staff Name','Discord Name','Discord ID','Training','Trainer','Training Date','Notes'],data.map(r=>[r.staff_name,r.discord_name,r.discord_id,r.training_name,r.trainer_name,r.training_date,r.notes]));};

async function renderBans(){
  setHead('Ban Logs','Track player bans and disciplinary records');const {data=[]}=await sb.from('bans').select('*').order('ban_date',{ascending:false}).order('created_at',{ascending:false});
  $('#content').innerHTML=panel('Ban Logs','SECURITY',`<div class="toolbar">${canWrite()?'<button class="btn danger" onclick="banForm()">+ Add Ban</button><button class="btn secondary" onclick="importCsvDialog(\'bans\')">Import CSV</button>':''}<button class="btn secondary" onclick="exportBans()">Export CSV</button><input id="banSearch" placeholder="Search name, Discord ID, reason..."></div><div id="banTable"></div>`);
  const draw=()=>{const q=$('#banSearch').value.toLowerCase();const rows=data.filter(r=>!q||[r.player_name,r.discord_id,r.reason,r.staff_name].join(' ').toLowerCase().includes(q));$('#banTable').innerHTML=table(['Date of Ban','Discord Name / Player','Discord ID','Reason','Duration','Banned By','Evidence','Status','Actions'],rows.map(r=>[dateOnly(r.ban_date),esc(r.player_name),code(r.discord_id),esc(r.reason),esc(r.duration_text),esc(r.staff_name),r.evidence?`<a class="clickable" href="${esc(r.evidence)}" target="_blank">Open</a>`:'—',badge(r.status,r.status==='Active'?'danger':''),standardActions('bans',r.id,'banForm')]))};$('#banSearch').oninput=draw;draw();
}
window.banForm=async id=>{let r={ban_date:today(),status:'Active'};if(id){const {data}=await sb.from('bans').select('*').eq('id',id).single();r=data||r;}openModal(`<h3>${id?'Edit':'Add'} Ban</h3><form id="banForm" class="form-grid">${field('Discord Name / Player','player_name',r.player_name,true)}${field('Discord ID','discord_id',r.discord_id)}${field('Citizen ID','citizen_id',r.citizen_id)}${field('License','license',r.license)}${field('Date of Ban','ban_date',dateOnly(r.ban_date)==='—'?today():dateOnly(r.ban_date),true,'date')}${field('Duration','duration_text',r.duration_text,true)}${field('Banned By','staff_name',r.staff_name,true)}${selectField('Status','status',['Active','Expired','Appealed','Removed'],r.status||'Active')}${field('Evidence URL','evidence',r.evidence)}${area('Reason','reason',r.reason,true)}<div class="full"><button class="btn danger">Save Ban</button></div></form>`);$('#banForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);o.server='NHRP';const res=id?await sb.from('bans').update(o).eq('id',id).select().single():await sb.from('bans').insert(o).select().single();if(res.error)return toast(res.error.message);await audit(id?'update':'create','ban',res.data.id,{name:o.player_name});closeModal();toast('Ban saved');renderBans();};};
window.exportBans=async()=>{const {data=[]}=await sb.from('bans').select('*').order('ban_date',{ascending:false});downloadCsv('nhrp_bans.csv',['Date of Ban','Discord Name / Player','Discord ID','Citizen ID','License','Reason','Duration','Banned By','Evidence','Status'],data.map(r=>[r.ban_date,r.player_name,r.discord_id,r.citizen_id,r.license,r.reason,r.duration_text,r.staff_name,r.evidence,r.status]));};

async function renderSpawnCodes(){
  setHead('Spawn Codes','Vehicle, item, job, ped, prop, and other spawn code library');const {data=[]}=await sb.from('spawn_codes').select('*').order('name');const categories=await getCategories('spawn_category','',data.map(r=>r.category).filter(Boolean));
  $('#content').innerHTML=panel('Spawn Codes','RECORDS',`<div class="toolbar">${canWrite()?'<button class="btn primary" onclick="spawnForm()">+ Add Entry</button><button class="btn secondary" onclick="importCsvDialog(\'spawn_codes\')">Import CSV</button>':''}<button class="btn secondary" onclick="exportSpawnCodes()">Export CSV</button><button class="btn secondary" onclick="downloadTemplate('spawn_codes')">CSV Template</button>${categoryButton('spawn_category')}<select id="spawnCategoryFilter"><option value="All">All Categories</option>${categories.map(t=>`<option value="${esc(t)}" ${state.spawnCategory===t?'selected':''}>${esc(t)}</option>`).join('')}</select><input id="spawnSearch" placeholder="Search name, code, pack, owner..."></div><div id="spawnTable"></div>`);
  const draw=()=>{const q=$('#spawnSearch').value.toLowerCase();const rows=data.filter(r=>(state.spawnCategory==='All'||r.category===state.spawnCategory)&&(!q||[r.name,r.spawn_code,r.category,r.pack,r.owner_name,r.notes].join(' ').toLowerCase().includes(q)));$('#spawnTable').innerHTML=table(['Name','Spawn Code','Category','Pack / Resource','Owner','Notes','Actions'],rows.map(r=>[esc(r.name),code(r.spawn_code),esc(r.category),esc(r.pack),esc(r.owner_name),esc(r.notes||'—'),standardActions('spawn_codes',r.id,'spawnForm')]))};$('#spawnSearch').oninput=draw;$('#spawnCategoryFilter').onchange=e=>{state.spawnCategory=e.target.value;draw();};draw();
}
window.setSpawnCategory=t=>{state.spawnCategory=t;renderSpawnCodes();};
window.spawnForm=async id=>{let r={category:state.spawnCategory==='All'?'Car / SUV':state.spawnCategory};if(id){const {data}=await sb.from('spawn_codes').select('*').eq('id',id).single();r=data||r;}const categories=await getCategories('spawn_category',r.category);openModal(`<h3>${id?'Edit':'Add'} Spawn Code</h3><form id="spawnForm" class="form-grid">${field('Name','name',r.name,true)}${field('Spawn Code','spawn_code',r.spawn_code,true)}${selectField('Category','category',categories,r.category)}${field('Pack / Resource','pack',r.pack)}${field('Owner','owner_name',r.owner_name)}${area('Notes','notes',r.notes)}<div class="full"><button class="btn primary">Save Entry</button></div></form>`);$('#spawnForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);o.server='NHRP';const res=id?await sb.from('spawn_codes').update(o).eq('id',id).select().single():await sb.from('spawn_codes').insert(o).select().single();if(res.error)return toast(res.error.message);await audit(id?'update':'create','spawn_codes',res.data.id,{spawn_code:o.spawn_code});closeModal();toast('Spawn code saved');renderSpawnCodes();};};
window.exportSpawnCodes=async()=>{let q=sb.from('spawn_codes').select('*').order('name');if(state.spawnCategory!=='All')q=q.eq('category',state.spawnCategory);const {data=[]}=await q;downloadCsv(`nhrp_spawn_codes_${slug(state.spawnCategory)}.csv`,['Name','Spawn Code','Category','Pack / Resource','Owner','Notes'],data.map(r=>[r.name,r.spawn_code,r.category,r.pack,r.owner_name,r.notes]));};

async function renderTCodes(){
  setHead('T/Codes','Quick-reference T/Codes with one-click copy');const {data=[]}=await sb.from('t_codes').select('*').order('category').order('code');const categories=await getCategories('tcode_category','',data.map(r=>r.category).filter(Boolean));
  $('#content').innerHTML=panel('T/Codes','RECORDS',`<div class="toolbar">${canWrite()?'<button class="btn primary" onclick="tCodeForm()">+ Add T/Code</button><button class="btn secondary" onclick="importCsvDialog(\'t_codes\')">Import CSV</button>':''}<button class="btn secondary" onclick="exportTCodes()">Export CSV</button><button class="btn secondary" onclick="downloadTemplate('t_codes')">CSV Template</button>${categoryButton('tcode_category')}<select id="tCodeCategory"><option value="">All Categories</option>${categories.map(x=>`<option>${esc(x)}</option>`).join('')}</select><input id="tCodeSearch" placeholder="Search code, description, category..."></div><div id="tCodeTable"></div>`);
  const draw=()=>{const q=$('#tCodeSearch').value.toLowerCase(),cat=$('#tCodeCategory').value;const rows=data.filter(r=>(!cat||r.category===cat)&&(!q||[r.code,r.description,r.category].join(' ').toLowerCase().includes(q)));$('#tCodeTable').innerHTML=table(['Code','Description','Category','Actions'],rows.map(r=>[code(r.code),esc(r.description),esc(r.category),standardActions('t_codes',r.id,'tCodeForm')]))};$('#tCodeSearch').oninput=draw;$('#tCodeCategory').onchange=draw;draw();
}
window.tCodeForm=async id=>{let r={category:'General'};if(id){const {data}=await sb.from('t_codes').select('*').eq('id',id).single();r=data||r;}const categories=await getCategories('tcode_category',r.category);openModal(`<h3>${id?'Edit':'Add'} T/Code</h3><form id="tCodeForm" class="form-grid">${field('Code','code',r.code,true)}${selectField('Category','category',categories,r.category||'General')}${area('Description','description',r.description,true)}<div class="full"><button class="btn primary">Save T/Code</button></div></form>`);$('#tCodeForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);const res=id?await sb.from('t_codes').update(o).eq('id',id).select().single():await sb.from('t_codes').insert(o).select().single();if(res.error)return toast(res.error.message);await audit(id?'update':'create','t_codes',res.data.id,{code:o.code});closeModal();toast('T/Code saved');renderTCodes();};};
window.exportTCodes=async()=>{const {data=[]}=await sb.from('t_codes').select('*').order('category').order('code');downloadCsv('nhrp_t_codes.csv',['Code','Description','Category'],data.map(r=>[r.code,r.description,r.category]));};

async function renderF9(){
  setHead('F9','Manage F9 coin shop entries');const {data=[]}=await sb.from('f9_items').select('*').order('name');const types=await getCategories('f9_type','',data.map(r=>r.type).filter(Boolean));
  $('#content').innerHTML=panel('F9','RECORDS',`<div class="toolbar">${canWrite()?'<button class="btn primary" onclick="f9Form()">+ Add F9 Item</button><button class="btn secondary" onclick="importCsvDialog(\'f9_items\')">Import CSV</button>':''}<button class="btn secondary" onclick="exportF9()">Export CSV</button><button class="btn secondary" onclick="downloadTemplate(\'f9_items\')">CSV Template</button>${categoryButton('f9_type')}<select id="f9TypeFilter"><option value="All">All Types</option>${types.map(t=>`<option value="${esc(t)}" ${state.f9Type===t?'selected':''}>${esc(t)}</option>`).join('')}</select><select id="f9CostFilter"><option value="All" ${state.f9Cost==='All'?'selected':''}>All Coin Costs</option><option value="0-300" ${state.f9Cost==='0-300'?'selected':''}>0–300</option><option value="301-500" ${state.f9Cost==='301-500'?'selected':''}>301–500</option><option value="501-700" ${state.f9Cost==='501-700'?'selected':''}>501–700</option><option value="701+" ${state.f9Cost==='701+'?'selected':''}>701+</option></select><input id="f9Search" placeholder="Search spawn code, name, type..."></div><div id="f9Table"></div>`);
  const costMatch=r=>{const c=Number(r.coin_cost||0);if(state.f9Cost==='0-300')return c<=300;if(state.f9Cost==='301-500')return c>=301&&c<=500;if(state.f9Cost==='501-700')return c>=501&&c<=700;if(state.f9Cost==='701+')return c>=701;return true;};
  const draw=()=>{const q=$('#f9Search').value.toLowerCase();const rows=data.filter(r=>(state.f9Type==='All'||r.type===state.f9Type)&&costMatch(r)&&(!q||[r.spawn_code,r.name,r.type,r.coin_cost].join(' ').toLowerCase().includes(q)));$('#f9Table').innerHTML=table(['Spawn Code','Name','Type','Coin Cost','Screenshot','Actions'],rows.map(r=>[code(r.spawn_code),esc(r.name),esc(r.type),Number(r.coin_cost||0).toLocaleString(),screenshotLink(r.screenshot_url),standardActions('f9_items',r.id,'f9Form')]))};$('#f9Search').oninput=draw;$('#f9TypeFilter').onchange=e=>{state.f9Type=e.target.value;draw();};$('#f9CostFilter').onchange=e=>{state.f9Cost=e.target.value;draw();};draw();
}
window.f9Form=async id=>{let r={coin_cost:0};if(id){const {data}=await sb.from('f9_items').select('*').eq('id',id).single();r=data||r;}const types=await getCategories('f9_type',r.type);openModal(`<h3>${id?'Edit':'Add'} F9 Item</h3><form id="f9Form" class="form-grid">${field('Spawn Code','spawn_code',r.spawn_code,true)}${field('Name','name',r.name,true)}${selectField('Type','type',types,r.type)}${field('Coin Cost','coin_cost',r.coin_cost,true,'number','1')}${screenshotDropField('f9Screenshot',r.screenshot_url)}<div class="full"><button class="btn primary">Save F9 Item</button></div></form>`);initScreenshotDrop('f9Screenshot','f9');$('#f9Form').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);o.coin_cost=Number(o.coin_cost||0);const res=id?await sb.from('f9_items').update(o).eq('id',id).select().single():await sb.from('f9_items').insert(o).select().single();if(res.error)return toast(res.error.message);await audit(id?'update':'create','f9_items',res.data.id,{spawn_code:o.spawn_code});closeModal();toast('F9 item saved');renderF9();};};
window.exportF9=async()=>{const {data=[]}=await sb.from('f9_items').select('*').order('name');downloadCsv('nhrp_f9.csv',['Spawn Code','Name','Type','Coin Cost','Screenshot'],data.map(r=>[r.spawn_code,r.name,r.type,r.coin_cost,r.screenshot_url]));};

async function renderStaff(){
  setHead('Staff Management','Manage NHRP staff records');const {data=[]}=await sb.from('staff').select('*').order('display_name');const ranks=await getCategories('staff_rank','',data.map(r=>r.rank).filter(Boolean));
  $('#content').innerHTML=panel('Staff Management','SERVER',`<div class="toolbar">${canWrite()?'<button class="btn primary" onclick="staffForm()">+ Add Staff</button><button class="btn secondary" onclick="importCsvDialog(\'staff\')">Import CSV</button>':''}<button class="btn secondary" onclick="exportStaff()">Export CSV</button>${categoryButton('staff_rank')}<select id="staffRank"><option value="">All Ranks</option>${ranks.map(x=>`<option>${esc(x)}</option>`).join('')}</select><input id="staffSearch" placeholder="Search name, Discord, rank..."></div><div id="staffTable"></div>`);
  const draw=()=>{const q=$('#staffSearch').value.toLowerCase(),rank=$('#staffRank').value;const rows=data.filter(r=>(!rank||r.rank===rank)&&(!q||[r.display_name,r.discord_name,r.discord_id,r.rank,r.status].join(' ').toLowerCase().includes(q)));$('#staffTable').innerHTML=table(['Name','Discord Name','Discord ID','Rank','Status','Hire Date','Movement Date','Actions'],rows.map(r=>[esc(r.display_name),esc(r.discord_name),code(r.discord_id),esc(r.rank),badge(r.status,r.status==='Inactive'||r.status==='Terminated'?'danger':''),dateOnly(r.hire_date),dateOnly(r.movement_date),standardActions('staff',r.id,'staffForm')]))};$('#staffSearch').oninput=draw;$('#staffRank').onchange=draw;draw();
}
window.staffForm=async id=>{let r={status:'Active',hire_date:today(),movement_date:today()};if(id){const {data}=await sb.from('staff').select('*').eq('id',id).single();r=data||r;}const ranks=await getCategories('staff_rank',r.rank);openModal(`<h3>${id?'Edit':'Add'} Staff</h3><form id="staffForm" class="form-grid">${field('Name','display_name',r.display_name,true)}${field('Discord Name','discord_name',r.discord_name)}${field('Discord ID','discord_id',r.discord_id)}${selectField('Rank','rank',ranks,r.rank)}${selectField('Status','status',['Active','LOA','Inactive','Terminated'],r.status||'Active')}${field('Hire Date','hire_date',dateOnly(r.hire_date)==='—'?today():dateOnly(r.hire_date),false,'date')}${field('Movement Date','movement_date',dateOnly(r.movement_date)==='—'?today():dateOnly(r.movement_date),false,'date')}${area('Notes','notes',r.notes)}<div class="full"><button class="btn primary">Save Staff</button></div></form>`);$('#staffForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);o.server='NHRP';const res=id?await sb.from('staff').update(o).eq('id',id).select().single():await sb.from('staff').insert(o).select().single();if(res.error)return toast(res.error.message);await audit(id?'update':'create','staff',res.data.id,{name:o.display_name,rank:o.rank});closeModal();toast('Staff saved');renderStaff();};};
window.exportStaff=async()=>{const {data=[]}=await sb.from('staff').select('*').order('display_name');downloadCsv('nhrp_staff.csv',['Name','Discord Name','Discord ID','Rank','Status','Hire Date','Movement Date','Notes'],data.map(r=>[r.display_name,r.discord_name,r.discord_id,r.rank,r.status,r.hire_date,r.movement_date,r.notes]));};

async function renderBackup(){
  setHead('Backup / Restore','Export or restore NHRP Command Center records');if(!ownerOnly())return $('#content').innerHTML='<div class="empty">Access denied.</div>';
  $('#content').innerHTML=panel('Backup / Restore','SYSTEM',`<div class="backup-box"><h3>Full Data Backup</h3><p class="muted">Downloads Businesses, Factions, Bans, Spawn Codes, 1 of 1, F9, Staff, Training, Payments, Housing, To-Dos, and activity history as one JSON file.</p><button class="btn primary" onclick="backupAll()">Download Backup</button></div><div class="backup-box"><h3>Restore Backup</h3><p class="muted">Restore a backup created by this Command Center. Existing IDs are updated; new IDs are inserted.</p><button class="btn secondary" onclick="restoreBackupDialog()">Choose Backup File</button></div>`);
}
window.backupAll=async()=>{const data={version:'NHRP-COMBINED-1',created_at:new Date().toISOString(),tables:{}};for(const t of APP_TABLES){const {data:rows=[],error}=await sb.from(t).select('*');if(error)return toast(`Backup failed on ${t}: ${error.message}`);data.tables[t]=rows;}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nhrp_command_center_backup_${today()}.json`;a.click();URL.revokeObjectURL(a.href);await audit('backup','system',null,{tables:APP_TABLES.length});toast('Backup downloaded');};
window.restoreBackupDialog=()=>{const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;if(!confirm('Restore this backup into the Command Center?'))return;try{const json=JSON.parse(await file.text());for(const t of APP_TABLES){const rows=json?.tables?.[t];if(!Array.isArray(rows)||!rows.length)continue;const {error}=await sb.from(t).upsert(rows,{onConflict:'id'});if(error)throw new Error(`${t}: ${error.message}`);}await audit('restore','system',null,{file:file.name});toast('Backup restored');renderDashboard();}catch(err){toast(err.message||'Restore failed');}};input.click();};

async function renderAudit(){
  setHead('Audit Log','Who changed what and when');if(!ownerOnly())return $('#content').innerHTML='<div class="empty">Access denied.</div>';const [{data:logs=[]},{data:profiles=[]}]=await Promise.all([sb.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(300),sb.from('profiles').select('id,display_name,discord_name')]);const names=Object.fromEntries(profiles.map(p=>[p.id,p.display_name||p.discord_name||p.id]));$('#content').innerHTML=panel('Audit Log','SYSTEM',table(['When','User','Action','Entity','ID','Details'],logs.map(r=>[datefmt(r.created_at),esc(names[r.user_id]||'Unknown'),esc(r.action),esc(r.entity_type),code(r.entity_id),`<span class="code">${esc(JSON.stringify(r.details||{}))}</span>`])));
}

async function renderUsers(){
  setHead('Users','Discord access and Command Center permissions');if(!ownerOnly())return $('#content').innerHTML='<div class="empty">Access denied.</div>';const [{data:reg=[]},{data:profiles=[]}]=await Promise.all([sb.from('access_registry').select('*').order('name'),sb.from('profiles').select('*').order('display_name')]);const linked=new Map(profiles.filter(p=>p.discord_id).map(p=>[p.discord_id,p]));const pending=profiles.filter(p=>!p.active&&!reg.some(r=>r.discord_id===p.discord_id));
  const body=`<div class="toolbar" style="margin-bottom:14px"><button class="btn primary" onclick="registryForm()">+ Add User</button></div>${table(['Name','Discord Name','Discord ID','Role','Movement Date','Access','Signed In','Actions'],reg.map(r=>{const p=linked.get(r.discord_id);return[esc(r.name),esc(r.discord_name||p?.discord_name),code(r.discord_id),badge(roleLabel(r.role)),dateOnly(r.movement_date),badge(r.active?'Approved':'Disabled',r.active?'':'danger'),p?'Yes':'Not Yet',`<div class="actions"><button class="btn secondary small" onclick="registryForm('${r.id}')">Edit</button><button class="btn secondary small" onclick="movementHistory('${r.discord_id}')">History</button><button class="btn danger small" onclick="deleteRow('access_registry','${r.id}')">Delete</button></div>`];}))}${pending.length?`<div class="panel-head" style="margin-top:20px"><div><div class="panel-kicker">PENDING</div><h2>Unapproved Sign-Ins</h2></div></div>${table(['Discord Name','Discord ID','Role','Actions'],pending.map(p=>[esc(p.discord_name||p.display_name),code(p.discord_id),esc(roleLabel(p.role)),`<button class="btn primary small" onclick="approvePending('${p.id}')">Review / Approve</button>`]))}`:''}`;$('#content').innerHTML=panel('Users','SYSTEM',body);
}
const userRoles=['owner','executive','director','admin','business_manager','developer','viewer'];
window.registryForm=async id=>{let r={active:true,role:'viewer',movement_date:today()};if(id){const {data}=await sb.from('access_registry').select('*').eq('id',id).single();r=data||r;}openModal(`<h3>${id?'Edit':'Add'} User</h3><form id="registryForm" class="form-grid">${field('Name','name',r.name,true)}${field('Discord Name','discord_name',r.discord_name)}${field('Discord ID','discord_id',r.discord_id,true)}${selectField('Role','role',userRoles.map(x=>({value:x,label:roleLabel(x)})),r.role)}${field('Movement Date','movement_date',dateOnly(r.movement_date)==='—'?today():dateOnly(r.movement_date),false,'date')}<label>Access<select name="active"><option value="true" ${r.active?'selected':''}>Approved</option><option value="false" ${!r.active?'selected':''}>Disabled</option></select></label>${area('Notes','notes',r.notes)}<div class="full"><button class="btn primary">${id?'Save User':'Add User'}</button></div></form>`);$('#registryForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);o.active=o.active==='true';const oldRole=r.role||null;const res=id?await sb.from('access_registry').update(o).eq('id',id).select().single():await sb.from('access_registry').insert({...o,created_by:state.user.id}).select().single();if(res.error)return toast(res.error.message);await sb.from('profiles').update({display_name:o.name,discord_name:o.discord_name,role:o.role,active:o.active,movement_date:o.movement_date}).eq('discord_id',o.discord_id);if(!id||oldRole!==o.role)await sb.from('user_movement_history').insert({discord_id:o.discord_id,name:o.name,discord_name:o.discord_name,from_role:id?oldRole:null,to_role:o.role,movement_date:o.movement_date||today(),change_type:id?'Role Change':'User Added',notes:o.notes,changed_by:state.user.id});await audit(id?'update':'create','access_registry',res.data.id,{discord_id:o.discord_id,role:o.role,active:o.active});closeModal();toast('User saved');renderUsers();};};
window.approvePending=async profileId=>{const {data:p,error}=await sb.from('profiles').select('*').eq('id',profileId).single();if(error)return toast(error.message);openModal(`<h3>Review / Approve User</h3><form id="approveForm" class="form-grid">${field('Name','name',p.display_name||'',true)}${field('Discord Name','discord_name',p.discord_name||'')}<label>Discord ID<input name="discord_id" value="${esc(p.discord_id||'')}" readonly></label>${selectField('Role','role',userRoles.map(x=>({value:x,label:roleLabel(x)})),p.role||'viewer')}${field('Movement Date','movement_date',today(),false,'date')}<div class="full"><button class="btn primary">Approve User</button></div></form>`);$('#approveForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target);const {data:r,error:ie}=await sb.from('access_registry').insert({...o,active:true,created_by:state.user.id}).select().single();if(ie)return toast(ie.message);const {error:ue}=await sb.from('profiles').update({display_name:o.name,discord_name:o.discord_name,role:o.role,active:true,movement_date:o.movement_date}).eq('id',profileId);if(ue)return toast(ue.message);await sb.from('user_movement_history').insert({discord_id:o.discord_id,name:o.name,discord_name:o.discord_name,from_role:p.role,to_role:o.role,movement_date:o.movement_date||today(),change_type:'Approved',changed_by:state.user.id});await audit('approve','profile',profileId,{discord_id:o.discord_id,role:o.role});closeModal();toast('User approved');renderUsers();};};
window.movementHistory=async discordId=>{const {data=[],error}=await sb.from('user_movement_history').select('*').eq('discord_id',discordId).order('movement_date',{ascending:false});if(error)return toast(error.message);openModal(`<h3>Movement History</h3>${table(['Movement Date','Change','From','To','Notes'],data.map(r=>[dateOnly(r.movement_date),esc(r.change_type),esc(roleLabel(r.from_role)||'—'),esc(roleLabel(r.to_role)||'—'),esc(r.notes||'—')]))}`);};

function renderSettings(){setHead('Settings','NHRP Command Center configuration');if(!ownerOnly())return $('#content').innerHTML='<div class="empty">Access denied.</div>';$('#content').innerHTML=panel('Settings','SYSTEM',`<div class="settings-list"><div class="setting-row"><span>Server</span><b>NHRP Only</b></div><div class="setting-row"><span>Authentication</span><b>Discord OAuth</b></div><div class="setting-row"><span>Activity Check Frequency</span><b>Every 30 Days</b></div><div class="setting-row"><span>Tracked Activity Categories</span><b>Business • Faction • Housing • 1 of 1</b></div><div class="setting-row"><span>Business Hours Method</span><b>Total Hours Per Check — No Clock In/Out</b></div><div class="setting-row"><span>Categories</span><b>Editable from each applicable tab</b></div></div>`);}

// ---------------- CSV helpers ----------------
function slug(v){return String(v||'all').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');}
function csvCell(v){const s=String(v??'');return /[",\n\r]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
function downloadCsv(filename,headers,rows){const text=[headers,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n');const blob=new Blob([text],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();URL.revokeObjectURL(a.href);}
function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++;}else if(c==='"')quoted=false;else field+=c;}else{if(c==='"')quoted=true;else if(c===','){row.push(field);field='';}else if(c==='\n'){row.push(field.replace(/\r$/,''));rows.push(row);row=[];field='';}else field+=c;}}if(field!==''||row.length){row.push(field.replace(/\r$/,''));rows.push(row);}return rows.filter(r=>r.some(v=>String(v).trim()!==''));}
function normalizeHeader(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'');}
function rowObjects(rows){if(rows.length<2)return[];const h=rows[0].map(normalizeHeader);return rows.slice(1).map(r=>Object.fromEntries(h.map((x,i)=>[x,String(r[i]??'').trim()])));}
function pick(o,...keys){for(const k of keys){const n=normalizeHeader(k);if(o[n]!==undefined&&o[n]!=='')return o[n];}return null;}
window.importCsvDialog=kind=>{const input=document.createElement('input');input.type='file';input.accept='.csv,text/csv';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{const rows=rowObjects(parseCsv(await file.text()));if(!rows.length)return toast('CSV has no data rows');await importRows(kind,rows);}catch(err){toast(err.message||'Import failed');}};input.click();};
async function importRows(kind,rows){
  let payload=[],tableName=kind,onConflict='id';
  if(kind==='spawn_codes'){payload=rows.map(o=>({name:pick(o,'Name'),spawn_code:pick(o,'Spawn Code','Spawncode'),category:pick(o,'Category','Type')||'Car / SUV',pack:pick(o,'Pack / Resource','Pack'),owner_name:pick(o,'Owner'),notes:pick(o,'Notes'),server:'NHRP'})).filter(x=>x.name&&x.spawn_code);tableName='spawn_codes';onConflict='server,spawn_code';}
  else if(kind==='one_of_ones'){payload=rows.map(o=>{const raw=String(pick(o,'Type')||'Vehicles');const added=normalizeDate(pick(o,'Date','Add Date'),today());const checked=normalizeDate(pick(o,'Date Checked','Last Activity Check','Activity Check Date'),null);return{discord_name:pick(o,'Discord Name'),discord_id:pick(o,'Discord ID'),type:raw,spawn_code:pick(o,'Spawn Code','Spawncode'),add_date:added,payment_method:pick(o,'Payment Method'),amount:Number(pick(o,'Amount')||0),status:pick(o,'Status')||'Active',last_activity_check:checked,next_activity_check:(pick(o,'Status')||'Active')==='Inactive'?null:addDaysIso(checked||added,30),notes:pick(o,'Notes'),screenshot_url:pick(o,'Screenshot','Screenshot URL')};}).filter(x=>x.discord_name&&x.discord_id&&x.spawn_code);tableName='one_of_ones';onConflict='spawn_code';}
  else if(kind==='t_codes'){payload=rows.map(o=>({code:pick(o,'Code','T/Code','T-Code'),description:pick(o,'Description'),category:pick(o,'Category')||'General'})).filter(x=>x.code&&x.description);tableName='t_codes';onConflict='code';}
  else if(kind==='f9_items'){payload=rows.map(o=>({spawn_code:pick(o,'Spawn Code','Spawncode'),name:pick(o,'Name'),type:pick(o,'Type'),coin_cost:Number(pick(o,'Coin Cost','Coins')||0),screenshot_url:pick(o,'Screenshot','Screenshot URL')})).filter(x=>x.spawn_code&&x.name&&x.type);tableName='f9_items';onConflict='spawn_code';}
  else if(kind==='housing'){payload=rows.map(o=>{const d=normalizeDate(pick(o,'Date Added','Date'),today());const checked=normalizeDate(pick(o,'Date Checked'),null);return{owner_name:pick(o,'Discord Name','Name'),discord_name:pick(o,'Discord Name','Name'),discord_id:pick(o,'Discord ID'),housing_tier:pick(o,'Housing Tier','Tier')||'Tier 1',postal:pick(o,'Postal'),price:Number(pick(o,'Price')||0),add_date:d,status:pick(o,'Status')||'Active',last_activity_check:checked,next_activity_check:addDaysIso(checked||d,30),screenshot_url:pick(o,'Screenshot','Screenshot URL'),server:'NHRP'};}).filter(x=>x.discord_name&&x.discord_id);tableName='housing';onConflict='id';}
  else if(kind==='businesses'){payload=rows.map(o=>{const p=normalizeDate(pick(o,'Purchase Date'),today());const checked=normalizeDate(pick(o,'Date Checked'),null);return{name:pick(o,'Business Name','Name'),type:pick(o,'Business Type','Type'),owner_name:pick(o,'Discord Name','Owner'),owner_discord_id:pick(o,'Discord ID'),job_code:pick(o,'Job Code'),postal:pick(o,'Postal'),purchase_date:p,total_hours_worked:Number(pick(o,'Total Hours Worked','Total Hours')||0),last_activity_check:checked,next_activity_check:addDaysIso(checked||p,30),status:pick(o,'Status')||'Active',notes:pick(o,'Notes'),screenshot_url:pick(o,'Screenshot','Screenshot URL'),server:'NHRP'};}).filter(x=>x.name);tableName='businesses';onConflict='id';}
  else if(kind==='factions'){payload=rows.map(o=>({name:pick(o,'Faction Name','Name'),type:pick(o,'Type'),leader_name:pick(o,'Leader Discord Name','Leader','Discord Name'),leader_discord_id:pick(o,'Leader Discord ID','Discord ID'),status:pick(o,'Status')||'Active',last_activity_check:normalizeDate(pick(o,'Date Checked'),null),next_activity_check:addDaysIso(normalizeDate(pick(o,'Date Checked'),null)||today(),30),notes:pick(o,'Notes'),screenshot_url:pick(o,'Screenshot','Screenshot URL'),server:'NHRP'})).filter(x=>x.name);tableName='factions';onConflict='id';}
  else if(kind==='bans'){payload=rows.map(o=>({ban_date:normalizeDate(pick(o,'Date of Ban','Ban Date'),today()),player_name:pick(o,'Discord Name / Player','Player','Name'),discord_id:pick(o,'Discord ID'),citizen_id:pick(o,'Citizen ID'),license:pick(o,'License'),reason:pick(o,'Reason')||'Imported Ban',duration_text:pick(o,'Duration')||'Unknown',staff_name:pick(o,'Banned By','Staff')||'Imported',evidence:pick(o,'Evidence'),status:pick(o,'Status')||'Active',server:'NHRP'})).filter(x=>x.player_name);tableName='bans';onConflict='id';}
  else if(kind==='staff'){payload=rows.map(o=>({display_name:pick(o,'Name'),discord_name:pick(o,'Discord Name'),discord_id:pick(o,'Discord ID'),rank:pick(o,'Rank'),status:pick(o,'Status')||'Active',hire_date:normalizeDate(pick(o,'Hire Date'),null),movement_date:normalizeDate(pick(o,'Movement Date'),null),notes:pick(o,'Notes'),server:'NHRP'})).filter(x=>x.display_name);tableName='staff';onConflict='id';}
  else if(kind==='staff_training'){payload=rows.map(o=>({staff_name:pick(o,'Staff Name','Name'),discord_name:pick(o,'Discord Name'),discord_id:pick(o,'Discord ID'),training_name:pick(o,'Training'),trainer_name:pick(o,'Trainer'),training_date:normalizeDate(pick(o,'Training Date','Date'),today()),notes:pick(o,'Notes')})).filter(x=>x.staff_name&&x.training_name);tableName='staff_training';onConflict='id';}
  else if(kind==='payments'){payload=rows.map(o=>({payer_name:pick(o,'Discord Name','Name')||'Imported',discord_name:pick(o,'Discord Name','Name'),discord_id:pick(o,'Discord ID'),payment_date:normalizeDate(pick(o,'Date'),today()),category:pick(o,'Category'),item_name:pick(o,'Add-In / Item','Item'),payment_method:pick(o,'Payment Method'),amount:Number(pick(o,'Amount')||0),notes:pick(o,'Notes'),screenshot_url:pick(o,'Screenshot','Screenshot URL'),server:'NHRP'})).filter(x=>x.discord_name);tableName='payments';onConflict='id';}
  else if(kind==='coin_collections'){payload=rows.map(o=>({username:pick(o,'Username','Name'),total_coins:Number(pick(o,'Total Coins','Coins')||0),collected:String(pick(o,'Collected')||'').toLowerCase()==='yes'||String(pick(o,'Collected')||'').toLowerCase()==='true'})).filter(x=>x.username);tableName='coin_collections';onConflict='username';}
  if(!payload.length)return toast('No valid rows found in the CSV.');
  const {error}=await sb.from(tableName).upsert(payload,{onConflict});if(error)return toast(error.message);await audit('import',tableName,null,{rows:payload.length});toast(`Imported ${payload.length} records`);render();
}
window.downloadTemplate=kind=>{const map={t_codes:[['Code','Description','Category'],[['10-4','Acknowledged','General']]],spawn_codes:[['Name','Spawn Code','Category','Pack / Resource','Owner','Notes'],[['Example Vehicle','examplecar','Car / SUV','Pack Name','',''],['Example Item','example_item','Items','Inventory Pack','','']]],one_of_ones:[['Discord Name','Discord ID','Type','Spawn Code','Date','Payment Method','Amount','Date Checked','Status','Notes','Screenshot URL'],[['falco_79','123456789','Vehicles','examplecar',today(),'PayPal','100','','Active','','']]],coin_collections:[['Username','Total Coins','Collected'],[['ExampleUser','1000','No']]],f9_items:[['Spawn Code','Name','Type','Coin Cost','Screenshot URL'],[['examplecar','Example Car','Cars/SUVs','250','']]],housing:[['Discord Name','Discord ID','Housing Tier','Postal','Price','Date Added','Date Checked','Status','Screenshot URL'],[['falco_79','123456789','Tier 2','123','250000',today(),'','Active','']]],factions:[['Faction Name','Type','Leader Discord Name','Leader Discord ID','Date Checked','Status','Notes','Screenshot URL'],[['Example Faction','Gang','falco_79','123456789','','Active','','']]]};const x=map[kind];if(!x)return;downloadCsv(`${kind}_template.csv`,x[0],x[1]);};

async function globalSearch(q){const like=`%${q}%`,out=[];const defs=[['businesses','name,owner_name,owner_discord_id,job_code','name','Business'],['factions','name,leader_name,leader_discord_id','name','Faction'],['bans','player_name,discord_id,reason','player_name','Ban'],['spawn_codes','name,spawn_code,pack','name','Spawn Code'],['t_codes','code,description,category','code','T/Code'],['one_of_ones','discord_name,discord_id,spawn_code','discord_name','1 of 1'],['f9_items','name,spawn_code,type','name','F9'],['staff','display_name,discord_name,discord_id,rank','display_name','Staff'],['housing','discord_name,owner_name,discord_id,postal','discord_name','Housing'],['coin_collections','username','username','Coin Collection']];for(const [t,cols,title,label] of defs){const {data=[]}=await sb.from(t).select('*').or(cols.split(',').map(c=>`${c}.ilike.${like}`).join(',')).limit(6);data.forEach(r=>out.push({title:r[title]||r.owner_name||'Record',sub:label}));}openModal(`<h3>Search Results</h3><div class="search-results">${out.length?out.map(x=>`<div class="search-result"><strong>${esc(x.title)}</strong><div class="muted">${esc(x.sub)}</div></div>`).join(''):'<div class="empty">No matches.</div>'}</div>`);}

boot();
